<?php

/**
 * @file
 * Implements core module functionality for ui hacks
 * @author Paulo Gomes <pauloamgomes@gmail.com>
 */


/**
 * ------------- hacks the text formats fieldset -------------------------------
 */

/**
 * Implements hook_element_info_alter().
 */
function empowered_ui_hacks_element_info_alter(&$type) {
  $type['text_format']['#process'][] = 'empowered_ui_hacks_element_process_text_format';
}

/**
 * Process function for text_format element.
 *
 * @see hook_element_info_alter().
 * @see https://drupal.org/node/2104275
 * @see https://chacadwa.com/blog/2013/12/23/collapse-text-format-descriptions-node-edit-form
 */
function empowered_ui_hacks_element_process_text_format($element) {
  $element['format']['#collapsible'] = TRUE;
  $element['format']['#collapsed'] = TRUE;
  $element['format']['#title'] = t('Text Format');
  $element['#attached']['css'][] = drupal_get_path('module', 'empowered_ui_hacks') . '/css/empowered_ui_hacks.css';

  return $element;
}
