<?php
/**
 * @file
 * empowered_basic_contents.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function empowered_basic_contents_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-basic_page-body'
  $field_instances['node-basic_page-body'] = array(
    'bundle' => 'basic_page',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'advanced_text_formatter',
        'settings' => array(
          'allowed_html' => array(
            0 => 'a',
            1 => 'b',
            2 => 'br',
            3 => 'dd',
            4 => 'dl',
            5 => 'dt',
            6 => 'em',
            7 => 'i',
            8 => 'li',
            9 => 'ol',
            10 => 'p',
            11 => 'strong',
            12 => 'u',
            13 => 'ul',
          ),
          'autop' => 0,
          'ellipsis' => 1,
          'filter' => 'input',
          'format' => 'plain_text',
          'token_replace' => 1,
          'trim_length' => 0,
          'use_summary' => 0,
          'word_boundary' => 1,
        ),
        'type' => 'advanced_text',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'show_token_tree' => FALSE,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');

  return $field_instances;
}
